/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Compra;
import dominio.Referencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nurcanc
 */
public class VistaCURegistrarCompra extends javax.swing.JPanel {
    protected ControlVistaRegistrarCompra c;
    /**
     * Creates new form VistaCURegistrarCompra
     */
    public VistaCURegistrarCompra() {
        initComponents();
        c=new ControlVistaRegistrarCompra(this);
    }

    protected boolean compruebaElementosCompra(){
        boolean val=true;
        
        /*Mirar si tienen los campos por defecto*/
        /*Mirar si los campos estan vacios*/
        if(getIdCompra()==0) val = false;
        
        return val;
    }
    protected int getIdCompra(){
        return Integer.parseInt(idCompraTextField.getText());
    }
    protected void setidComLabel(int idCompra){
        this.idComLabel.setText("idCompra");
    }
    protected void setNombreBodegaLabel(String nombreBodega){
        this.nombreBodegaLabel.setText(nombreBodega);    
    }
    protected void setUnidadesLabel(int unidades){
        this.unidadesLabel.setText("unidades");
    }
    public void lanzaError(String msg){
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    public void setComprobarEnabled(){
        this.comprobarButton.setEnabled(true);
    } 
    public void setSeleccionarEnabled(){
        this.selectionButton.setEnabled(true);
    }
    
    public void setFinalizarEnabled(boolean enabled){
        this.finalizarButton.setEnabled(enabled);
    }
    protected void showInforme(Referencia ref){

    }
    protected void mostrarTablas(boolean show){

    }
    private void comprobarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
         /*Comprobamos los campos*/
        if(compruebaElementosCompra()){
            /*Procesamos la comprobacion de abonado*/
           c.comprobarIDCompra();
           
        }else{
            lanzaError("Identificador de compra vacio(s)\no con el valor por defecto");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CompraLabel = new javax.swing.JLabel();
        iDCompraLabel = new javax.swing.JLabel();
        comprobarButton = new javax.swing.JButton();
        idCompraTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        idComLabel = new javax.swing.JLabel();
        nombreBodegaLabel = new javax.swing.JLabel();
        unidadesLabel = new javax.swing.JLabel();
        selectionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        finalizarButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        CompraLabel.setText("Compra");

        iDCompraLabel.setText("IDCompra");

        comprobarButton.setText("Comprobar");

        idCompraTextField.setText(" idCompra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(CompraLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iDCompraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comprobarButton)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CompraLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDCompraLabel)
                    .addComponent(idCompraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(comprobarButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        idComLabel.setText("iDCompra");

        nombreBodegaLabel.setText("nombreBodega");

        unidadesLabel.setText("unidades");

        selectionButton.setText("seleccionar");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigo", "cajas", "contenidoENCL", "precio", "disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        finalizarButton.setText("finalizar");

        volverButton.setText("volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(selectionButton)
                .addGap(76, 76, 76)
                .addComponent(finalizarButton)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(unidadesLabel))
                            .addComponent(nombreBodegaLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(idComLabel))))
                    .addComponent(volverButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idComLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreBodegaLabel)
                .addGap(12, 12, 12)
                .addComponent(unidadesLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionButton)
                    .addComponent(finalizarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompraLabel;
    private javax.swing.JTable Table;
    private javax.swing.JButton comprobarButton;
    private javax.swing.JButton finalizarButton;
    private javax.swing.JLabel iDCompraLabel;
    private javax.swing.JLabel idComLabel;
    private javax.swing.JTextField idCompraTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreBodegaLabel;
    private javax.swing.JButton selectionButton;
    private javax.swing.JLabel unidadesLabel;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
