/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author nurcanc
 */
public class VistaCUProcesarPedido extends javax.swing.JFrame {
    protected ControlVistaProcesarPedido c;
    /**
     * Creates new form VistaCUProcesarPedido
     */
    public VistaCUProcesarPedido() {
        initComponents();
        c=new ControlVistaProcesarPedido(this);
    }
     protected boolean compruebaElementosAbonado(){
        boolean val=true;
        
        /*Mirar si tienen los campos por defecto*/
        
        /*Mirar si los campos estan vacios*/
       if(getNumAbonado()==0) return val=false;
        
        return val;
    }
    protected boolean compruebaElementosPedido(){
        boolean val=true;
        
        /*Mirar si tienen los campos por defecto*/
        
        /*Mirar si los campos estan vacios*/
       if(getReferencia()==0 || getCantidad()==0) return val=false;
        
        return val;
    }
   protected int getNumAbonado(){
      return Integer.parseInt(nAbonadoField.getText());
    }
    
    protected int getReferencia(){
        return Integer.parseInt(referenciaField.getText());
    }
    
    protected int getCantidad(){
        return Integer.parseInt(cantidadField.getText());
    }
    

    public void lanzaError(String msg){
        JOptionPane.showMessageDialog(this, msg, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numAbLabel = new javax.swing.JLabel();
        ComprobarButton = new javax.swing.JButton();
        nAbonadoField = new javax.swing.JTextField();
        refLabel = new javax.swing.JLabel();
        referenciaField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        cantidadField = new javax.swing.JTextField();
        GuardarButton = new javax.swing.JButton();
        ConfirmarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("               PEDIDO");

        numAbLabel.setText("Numero Abonado");

        ComprobarButton.setText("Comprobar");

        nAbonadoField.setText("num abonado");
        nAbonadoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nAbonadoFieldActionPerformed(evt);
            }
        });

        refLabel.setText("Referencia");

        referenciaField.setText("referencia");
        referenciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaFieldActionPerformed(evt);
            }
        });

        totalLabel.setText("Cantidad");

        cantidadField.setText("cantidad");

        GuardarButton.setText("Guardar");

        ConfirmarButton.setText("Confirmar");

        javax.swing.GroupLayout PedidoLayout = new javax.swing.GroupLayout(Pedido);
        Pedido.setLayout(PedidoLayout);
        PedidoLayout.setHorizontalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refLabel)
                            .addComponent(totalLabel))
                        .addGap(51, 51, 51)
                        .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(referenciaField)
                            .addComponent(cantidadField)))
                    .addGroup(PedidoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(GuardarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComprobarButton)
                    .addComponent(numAbLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nAbonadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmarButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        PedidoLayout.setVerticalGroup(
            PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAbLabel)
                    .addComponent(nAbonadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprobarButton)
                    .addComponent(ConfirmarButton))
                .addGap(18, 18, 18)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refLabel)
                    .addComponent(referenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ComprobarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        /*Comprobamos los campos*/
        if(compruebaElementosAbonado()){
            /*Procesamos la comprobacion de abonado*/
           c.comprobarAbonado();
        }else{
            lanzaError("Número de abonado vacio(s)\no con el valor por defecto");
        }
    }                                             
     private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        /*Comprobamos los campos*/
        if(compruebaElementosPedido()){
            /*Procesamos la los datos del pedido*/
           c.comprobarPedido();
        }else{
            lanzaError("Número de referencia y la cantidad vacio(s)\no con el valor por defecto");
        }
    }
    private void ConfirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.dispose();
    }  
    private void nAbonadoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nAbonadoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nAbonadoFieldActionPerformed

    private void referenciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCUProcesarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCUProcesarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCUProcesarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCUProcesarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCUProcesarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComprobarButton;
    private javax.swing.JButton ConfirmarButton;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JPanel Pedido;
    private javax.swing.JTextField cantidadField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nAbonadoField;
    private javax.swing.JLabel numAbLabel;
    private javax.swing.JLabel refLabel;
    private javax.swing.JTextField referenciaField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
