/*TABLA CATEGORIA*/
INSERT INTO CATEGORIA VALUES('A','del año');
INSERT INTO CATEGORIA VALUES('C','crianza');
INSERT INTO CATEGORIA VALUES('R','reserva');
INSERT INTO CATEGORIA VALUES('G','gran reserva');

/*TABLA ESTADOPEDIDO*/
INSERT INTO ESTADOPEDIDO VALUES('P','pendiente');
INSERT INTO ESTADOPEDIDO VALUES('T','tramitado');
INSERT INTO ESTADOPEDIDO VALUES('C','completado');
INSERT INTO ESTADOPEDIDO VALUES('S','servido');
INSERT INTO ESTADOPEDIDO VALUES('F','facturado');
INSERT INTO ESTADOPEDIDO VALUES('A','abonado');

/*TABLA ESTADOFACTURA*/
INSERT INTO ESTADOFACTURA VALUES('E','emitida');
INSERT INTO ESTADOFACTURA VALUES('V','vencida');
INSERT INTO ESTADOFACTURA VALUES('P','pagada');
